[workspace.package]
license = "MIT-0"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://paritytech.github.io/polkadot-sdk/"
repository = "https://github.com/paritytech/polkadot-sdk-solochain-template.git"
edition = "2021"

[workspace]
members = [
    "node",
    "runtime",
]
resolver = "2"

[workspace.dependencies]
solochain-template-runtime = { path = "./runtime", default-features = false }
clap = { version = "4.5.13" }
frame-benchmarking-cli = { version = "48", default-features = false }
frame-metadata-hash-extension = { version = "0.9", default-features = false }
frame-system = { version = "41", default-features = false }
futures = { version = "0.3.31" }
jsonrpsee = { version = "0.24" }
pallet-transaction-payment = { version = "41", default-features = false }
pallet-transaction-payment-rpc = { version = "44", default-features = false }
sc-basic-authorship = { version = "0.50", default-features = false }
sc-cli = { version = "0.52", default-features = false }
sc-client-api = { version = "40", default-features = false }
sc-consensus = { version = "0.49", default-features = false }
sc-consensus-aura = { version = "0.50", default-features = false }
sc-consensus-grandpa = { version = "0.35", default-features = false }
sc-executor = { version = "0.43", default-features = false }
sc-network = { version = "0.50", default-features = false }
sc-offchain = { version = "45", default-features = false }
sc-service = { version = "0.51", default-features = false }
sc-telemetry = { version = "29", default-features = false }
sc-transaction-pool = { version = "40", default-features = false }
sc-transaction-pool-api = { version = "40", default-features = false }
sp-api = { version = "37", default-features = false }
sp-block-builder = { version = "37", default-features = false }
sp-blockchain = { version = "40", default-features = false }
sp-consensus-aura = { version = "0.43", default-features = false }
sp-core = { version = "37", default-features = false }
sp-genesis-builder = { version = "0.18", default-features = false }
sp-inherents = { version = "37", default-features = false }
sp-io = { version = "41", default-features = false }
sp-keyring = { version = "42", default-features = false }
sp-runtime = { version = "42", default-features = false }
sp-timestamp = { version = "37", default-features = false }
substrate-frame-rpc-system = { version = "44", default-features = false }
substrate-build-script-utils = { version = "12", default-features = false }
codec = { version = "3.6", default-features = false, package = "parity-scale-codec" }
frame-benchmarking = { version = "41", default-features = false }
frame-executive = { version = "41", default-features = false }
frame-support = { version = "41", default-features = false }
frame-system-benchmarking = { version = "41", default-features = false }
frame-system-rpc-runtime-api = { version = "37", default-features = false }
frame-try-runtime = { version = "0.47", default-features = false }
pallet-aura = { version = "40", default-features = false }
pallet-balances = { version = "42", default-features = false }
pallet-grandpa = { version = "41", default-features = false }
pallet-sudo = { version = "41", default-features = false }
pallet-timestamp = { version = "40", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "41", default-features = false }
scale-info = { version = "2.11", default-features = false }
serde_json = { version = "1.0", default-features = false }
sp-consensus-grandpa = { version = "24", default-features = false }
sp-offchain = { version = "37", default-features = false }
sp-session = { version = "39", default-features = false }
sp-storage = { version = "23", default-features = false }
sp-transaction-pool = { version = "37", default-features = false }
sp-version = { version = "40", default-features = false }
substrate-wasm-builder = { version = "27", default-features = false }

# Additional dependencies for custom pallets
sha3 = { version = "0.10", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
pallet-assets = { version = "41.0.0", default-features = false }

[profile.release]
opt-level = 3
panic = "unwind"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true

