[package]
authors = ['Manta Network']
edition = "2021"
homepage = "https://manta.network"
license = "GPL-3.0"
name = "pallet-farming-rpc-runtime-api"
repository = 'https://github.com/Manta-Network/Manta/'
version = "4.6.0"

[dependencies]
codec = { workspace = true }

sp-api = { workspace = true }
sp-std = { workspace = true }

manta-primitives = { workspace = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-api/std",
  "manta-primitives/std",
]
