version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["P-medium"]
    # NOTE: We update upstream manually.
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "pallet-*"
      - dependency-name: "cumulus-*"
      - dependency-name: "parachain-*"
      - dependency-name: "manta-*"
      - dependency-name: "orml-*"
      - dependency-name: "xcm*"
    schedule:
      interval: "weekly"
