// Copyright 2020-2023 Manta Network.
// This file is part of Manta.
//
// Manta is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Manta is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Manta.  If not, see <http://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_lottery
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-07-08, STEPS: `25`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("/home/runner/runners/2.280.1/_work/Manta/Manta/tests/data/fork.json"), DB CACHE: 1024

// Executed Command:
// ./target/production/manta
// benchmark
// pallet
// --chain=/home/runner/runners/2.280.1/_work/Manta/Manta/tests/data/fork.json
// --steps=25
// --repeat=20
// --pallet=pallet_lottery
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./scripts/benchmarking/frame-weights-output/pallet_lottery.rs
// --template=.github/resources/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;
use manta_primitives::constants::RocksDbWeight;

/// Weight functions needed for pallet_lottery.
pub trait WeightInfo {
    fn deposit(x: u32, y: u32, ) -> Weight;
    fn request_withdraw(x: u32, y: u32, ) -> Weight;
    fn claim_my_winnings(y: u32, ) -> Weight;
    fn start_lottery() -> Weight;
    fn stop_lottery() -> Weight;
    fn draw_lottery(x: u32, y: u32, ) -> Weight;
    fn process_matured_withdrawals() -> Weight;
    fn set_min_deposit() -> Weight;
    fn set_min_withdraw() -> Weight;
    fn set_gas_reserve() -> Weight;
}

/// Weights for pallet_lottery using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_lottery::WeightInfo for SubstrateWeight<T> {
	// Storage: Lottery MinDeposit (r:1 w:0)
	// Storage: Scheduler Lookup (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: ParachainStaking SelectedCandidates (r:1 w:0)
	// Storage: Lottery UnstakingCollators (r:1 w:0)
	// Storage: Lottery StakedCollators (r:2 w:1)
	// Storage: ParachainStaking CandidateInfo (r:2 w:1)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:1)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
	// Storage: ParachainStaking TopDelegations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Lottery ActiveBalancePerUser (r:1 w:1)
	// Storage: Lottery TotalPot (r:1 w:1)
	// Storage: Lottery TotalUsers (r:1 w:1)
	// Storage: Lottery SumOfDeposits (r:1 w:1)
	// Storage: ParachainStaking DelegationScheduledRequests (r:1 w:0)
	/// The range of component `x` is `[0, 1000]`.
	/// The range of component `y` is `[0, 63]`.
	fn deposit(x: u32, _y: u32, ) -> Weight {
		// Minimum execution time: 173_719 nanoseconds.
		Weight::from_ref_time(314_790_135)
			// Standard Error: 9_780
			.saturating_add(Weight::from_ref_time(187_432).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(23))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	// Storage: Lottery MinWithdraw (r:1 w:0)
	// Storage: Scheduler Lookup (r:1 w:0)
	// Storage: Lottery ActiveBalancePerUser (r:1 w:1)
	// Storage: Lottery WithdrawalRequestQueue (r:1 w:1)
	// Storage: Lottery TotalUsers (r:1 w:1)
	// Storage: Lottery TotalPot (r:1 w:1)
	// Storage: Lottery SurplusUnstakingBalance (r:1 w:1)
	// Storage: Lottery StakedCollators (r:2 w:1)
	// Storage: Lottery UnstakingCollators (r:1 w:1)
	// Storage: ParachainStaking SelectedCandidates (r:1 w:0)
	// Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:1)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: ParachainStaking DelegationScheduledRequests (r:1 w:1)
	/// The range of component `x` is `[0, 1000]`.
	/// The range of component `y` is `[0, 63]`.
	fn request_withdraw(x: u32, _y: u32, ) -> Weight {
		// Minimum execution time: 113_413 nanoseconds.
		Weight::from_ref_time(145_503_071)
			// Standard Error: 10_039
			.saturating_add(Weight::from_ref_time(131_226).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	// Storage: Lottery UnclaimedWinningsByAccount (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Lottery SumOfDeposits (r:1 w:0)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:1)
	/// The range of component `y` is `[0, 63]`.
	fn claim_my_winnings(y: u32, ) -> Weight {
		// Minimum execution time: 52_543 nanoseconds.
		Weight::from_ref_time(55_733_062)
			// Standard Error: 2_686
			.saturating_add(Weight::from_ref_time(141_791).saturating_mul(y.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: System Account (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:0)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: Lottery GasReserve (r:1 w:0)
	// Storage: Scheduler Agenda (r:1 w:1)
	fn start_lottery() -> Weight {
		// Minimum execution time: 91_113 nanoseconds.
		Weight::from_ref_time(92_722_000)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	fn stop_lottery() -> Weight {
		// Minimum execution time: 28_796 nanoseconds.
		Weight::from_ref_time(42_348_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: System Account (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:0)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:1)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: Lottery GasReserve (r:1 w:0)
	// Storage: Lottery SumOfDeposits (r:1 w:0)
	// Storage: Lottery TotalPot (r:1 w:0)
	// Storage: Lottery ActiveBalancePerUser (r:2 w:0)
	// Storage: Lottery UnclaimedWinningsByAccount (r:1 w:1)
	// Storage: Lottery UnstakingCollators (r:1 w:0)
	// Storage: Lottery WithdrawalRequestQueue (r:1 w:0)
	/// The range of component `x` is `[0, 1000]`.
	/// The range of component `y` is `[0, 63]`.
	fn draw_lottery(x: u32, y: u32, ) -> Weight {
		// Minimum execution time: 77_755 nanoseconds.
		Weight::from_ref_time(78_365_000)
			// Standard Error: 84_572
			.saturating_add(Weight::from_ref_time(4_109_255).saturating_mul(x.into()))
			// Standard Error: 1_345_540
			.saturating_add(Weight::from_ref_time(819_291).saturating_mul(y.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(x.into())))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Lottery UnstakingCollators (r:1 w:0)
	// Storage: Lottery WithdrawalRequestQueue (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	fn process_matured_withdrawals() -> Weight {
		// Minimum execution time: 13_551 nanoseconds.
		Weight::from_ref_time(13_771_000)
			.saturating_add(T::DbWeight::get().reads(3))
	}
	// Storage: Lottery MinWithdraw (r:1 w:0)
	// Storage: Lottery MinDeposit (r:0 w:1)
	fn set_min_deposit() -> Weight {
		// Minimum execution time: 25_043 nanoseconds.
		Weight::from_ref_time(26_070_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Lottery MinWithdraw (r:0 w:1)
	fn set_min_withdraw() -> Weight {
		// Minimum execution time: 9_657 nanoseconds.
		Weight::from_ref_time(14_980_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Lottery GasReserve (r:0 w:1)
	fn set_gas_reserve() -> Weight {
		// Minimum execution time: 9_195 nanoseconds.
		Weight::from_ref_time(9_761_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Lottery MinDeposit (r:1 w:0)
	// Storage: Scheduler Lookup (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: ParachainStaking SelectedCandidates (r:1 w:0)
	// Storage: Lottery UnstakingCollators (r:1 w:0)
	// Storage: Lottery StakedCollators (r:2 w:1)
	// Storage: ParachainStaking CandidateInfo (r:2 w:1)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:1)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
	// Storage: ParachainStaking TopDelegations (r:1 w:1)
	// Storage: ParachainStaking CandidatePool (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: ParachainStaking Total (r:1 w:1)
	// Storage: Lottery ActiveBalancePerUser (r:1 w:1)
	// Storage: Lottery TotalPot (r:1 w:1)
	// Storage: Lottery TotalUsers (r:1 w:1)
	// Storage: Lottery SumOfDeposits (r:1 w:1)
	// Storage: ParachainStaking DelegationScheduledRequests (r:1 w:0)
	/// The range of component `x` is `[0, 1000]`.
	/// The range of component `y` is `[0, 63]`.
	fn deposit(x: u32, _y: u32, ) -> Weight {
		// Minimum execution time: 173_719 nanoseconds.
		Weight::from_ref_time(314_790_135)
			// Standard Error: 9_780
			.saturating_add(Weight::from_ref_time(187_432).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(23))
			.saturating_add(RocksDbWeight::get().writes(13))
	}
	// Storage: Lottery MinWithdraw (r:1 w:0)
	// Storage: Scheduler Lookup (r:1 w:0)
	// Storage: Lottery ActiveBalancePerUser (r:1 w:1)
	// Storage: Lottery WithdrawalRequestQueue (r:1 w:1)
	// Storage: Lottery TotalUsers (r:1 w:1)
	// Storage: Lottery TotalPot (r:1 w:1)
	// Storage: Lottery SurplusUnstakingBalance (r:1 w:1)
	// Storage: Lottery StakedCollators (r:2 w:1)
	// Storage: Lottery UnstakingCollators (r:1 w:1)
	// Storage: ParachainStaking SelectedCandidates (r:1 w:0)
	// Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:1)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: ParachainStaking DelegationScheduledRequests (r:1 w:1)
	/// The range of component `x` is `[0, 1000]`.
	/// The range of component `y` is `[0, 63]`.
	fn request_withdraw(x: u32, _y: u32, ) -> Weight {
		// Minimum execution time: 113_413 nanoseconds.
		Weight::from_ref_time(145_503_071)
			// Standard Error: 10_039
			.saturating_add(Weight::from_ref_time(131_226).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(17))
			.saturating_add(RocksDbWeight::get().writes(9))
	}
	// Storage: Lottery UnclaimedWinningsByAccount (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Lottery SumOfDeposits (r:1 w:0)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:1)
	/// The range of component `y` is `[0, 63]`.
	fn claim_my_winnings(y: u32, ) -> Weight {
		// Minimum execution time: 52_543 nanoseconds.
		Weight::from_ref_time(55_733_062)
			// Standard Error: 2_686
			.saturating_add(Weight::from_ref_time(141_791).saturating_mul(y.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: System Account (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:0)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: Lottery GasReserve (r:1 w:0)
	// Storage: Scheduler Agenda (r:1 w:1)
	fn start_lottery() -> Weight {
		// Minimum execution time: 91_113 nanoseconds.
		Weight::from_ref_time(92_722_000)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	fn stop_lottery() -> Weight {
		// Minimum execution time: 28_796 nanoseconds.
		Weight::from_ref_time(42_348_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: System Account (r:1 w:0)
	// Storage: ParachainStaking DelegatorState (r:1 w:0)
	// Storage: Lottery TotalUnclaimedWinnings (r:1 w:1)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	// Storage: Lottery GasReserve (r:1 w:0)
	// Storage: Lottery SumOfDeposits (r:1 w:0)
	// Storage: Lottery TotalPot (r:1 w:0)
	// Storage: Lottery ActiveBalancePerUser (r:2 w:0)
	// Storage: Lottery UnclaimedWinningsByAccount (r:1 w:1)
	// Storage: Lottery UnstakingCollators (r:1 w:0)
	// Storage: Lottery WithdrawalRequestQueue (r:1 w:0)
	/// The range of component `x` is `[0, 1000]`.
	/// The range of component `y` is `[0, 63]`.
	fn draw_lottery(x: u32, y: u32, ) -> Weight {
		// Minimum execution time: 77_755 nanoseconds.
		Weight::from_ref_time(78_365_000)
			// Standard Error: 84_572
			.saturating_add(Weight::from_ref_time(4_109_255).saturating_mul(x.into()))
			// Standard Error: 1_345_540
			.saturating_add(Weight::from_ref_time(819_291).saturating_mul(y.into()))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(x.into())))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: Lottery UnstakingCollators (r:1 w:0)
	// Storage: Lottery WithdrawalRequestQueue (r:1 w:0)
	// Storage: Lottery UnlockedUnstakingFunds (r:1 w:0)
	fn process_matured_withdrawals() -> Weight {
		// Minimum execution time: 13_551 nanoseconds.
		Weight::from_ref_time(13_771_000)
			.saturating_add(RocksDbWeight::get().reads(3))
	}
	// Storage: Lottery MinWithdraw (r:1 w:0)
	// Storage: Lottery MinDeposit (r:0 w:1)
	fn set_min_deposit() -> Weight {
		// Minimum execution time: 25_043 nanoseconds.
		Weight::from_ref_time(26_070_000)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: Lottery MinWithdraw (r:0 w:1)
	fn set_min_withdraw() -> Weight {
		// Minimum execution time: 9_657 nanoseconds.
		Weight::from_ref_time(14_980_000)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: Lottery GasReserve (r:0 w:1)
	fn set_gas_reserve() -> Weight {
		// Minimum execution time: 9_195 nanoseconds.
		Weight::from_ref_time(9_761_000)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
