[package]
name = "manta-primitives"
version = "3.0.0"
edition = "2018"

[dependencies]
sp-core = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0'}
sp-std = { version = "3.0.0", default-features = false }
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

[features]
default = ['std']
std = [
    "codec/std",
    "serde",
    'sp-core/std',
    'sp-runtime/std',
    "sp-std/std",
]