[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pallet-farming-rpc-api"
repository.workspace = true
version.workspace = true

[dependencies]
codec = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true, features = ["derive"] }

sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-core = { workspace = true }
sp-rpc = { workspace = true }
sp-runtime = { workspace = true }

manta-primitives = { workspace = true }
pallet-farming-rpc-runtime-api = { workspace = true }
