[package]
name = "pallet-staking-reward-fn"
version = "4.0.0-dev"
authors = ['Manta Network']
edition = "2018"
license = "Apache-2.0"
homepage = "https://manta.network"
repository = 'https://github.com/Manta-Network/Manta/'
description = "Reward function for FRAME staking pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]

[dependencies]
sp-arithmetic = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/arithmetic" }
log = { version = "0.4.14", default-features = false }

[features]
default = ["std"]
std = [
	"sp-arithmetic/std",
	"log/std",
]
