[settings]
timeout = 300

[relaychain]
chain = "rococo-local"
default_command = "/home/jamie/my-repo/forks/jdeng/Manta/zombienet/polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9911

[[parachains]]
chain = "calamari-local"
# chain_spec_file = ""
cumulus_based = true
id = 2084

[[parachains.collators]]
command = "/home/jamie/my-repo/forks/jdeng/Manta/zombienet/manta"
name = "Alice" # cannot use alice here, alice has been occupied by one of relaychain node
validator = true
rcp_port = 9967
ws_port = 9921

[[parachains.collators]]
command = "/home/jamie/my-repo/forks/jdeng/Manta/zombienet/manta"
name = "Bob"
validator = true

[[parachains.collators]]
command = "/home/jamie/my-repo/forks/jdeng/Manta/zombienet/manta"
name = "Charlie"
validator = true

[[parachains.collators]]
command = "/home/jamie/my-repo/forks/jdeng/Manta/zombienet/manta"
name = "Dave"
validator = true

[[parachains.collators]]
command = "/home/jamie/my-repo/forks/jdeng/Manta/zombienet/manta"
name = "Eve"
validator = true
