#!/bin/sh
# Copyright Manta Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT

if [ "$1" = "purge" ]; then
    if getent passwd manta > /dev/null 2>&1; then
        deluser --system --remove-home manta
        echo "deluser manta, result: $?"
    fi
    if getent group manta > /dev/null 2>&1; then
        delgroup --system manta
        echo "delgroup manta, result: $?"
    fi
fi
