#!/bin/sh

set -e

action="$1"

chmod +x /usr/bin/manta

if [ "$action" = "configure" ]; then
    if ! getent group manta > /dev/null 2>&1; then
        addgroup --system manta
        echo "addgroup manta, result: $?"
    fi
    if ! getent passwd manta > /dev/null 2>&1; then
        adduser \
            --system \
            --home /var/lib/substrate \
            --disabled-password \
            --ingroup manta \
            manta
        echo "adduser manta, result: $?"
    fi
fi
