#!/bin/sh

set -e

action="$1"
config_file="/etc/default/manta"

chmod +x /usr/bin/manta

if [ "$action" = "configure" ]; then
  getent group manta > /dev/null 2>&1 || addgroup \
    --system \
    manta
  getent passwd manta > /dev/null 2>&1 || adduser \
    --system \
    --home /var/lib/substrate \
    --disabled-password \
    --ingroup manta \
    manta
fi
