[package]
name = "pallet-staking-reward-curve"
version = "4.0.0-dev"
authors = ['Manta Network']
edition = "2018"
license = "Apache-2.0"
homepage = "https://manta.network"
repository = 'https://github.com/Manta-Network/Manta/'
description = "Reward Curve for FRAME staking pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.58", features = ["full", "visit"] }
quote = "1.0.3"
proc-macro2 = "1.0.28"
proc-macro-crate = "1.0.0"

[dev-dependencies]
sp-runtime = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
