---

# yamllint disable rule:line-length

name: Security Audit

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

# yamllint enable rule:line-length
