name: docker-image-build

on:
  workflow_run:
    workflows: ["publish draft releases"]
    types: 
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MANTABOT_DOCKER_USERNAME }}
          password: ${{ secrets.MANTABOT_DOCKER_TOKEN }}

      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/calamari.Dockerfile
          tags: |
            mantanetwork/calamari:latest
            mantanetwork/calamari:${{ github.event.release.tag_name }}
          build-args: TAG_NAME=${{ github.event.release.tag_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
