name: create relay genesis files
on:
  workflow_dispatch:
    inputs:
      chain:
        description: The name of the chain to generate files for
        required: true
      version:
        description: A **released** version of manta to generate the genesis files from in the form vX.Y.Z
        required: true
env:
  CHAIN: ${{github.event.inputs.chain}}
  VERSION: ${{github.event.inputs.version}}
jobs:
  export_genesis_files:
    runs-on: ubuntu-latest
    steps:
      - name: get curl
        run: |
          apt update
          apt install -y curl
      - name: fetch and chmod manta release
        run: |
          curl -L -o $HOME/manta https://github.com/Manta-Network/Manta/releases/download/$VERSION/manta
          chmod +x $HOME/manta
          ls -ahl $HOME
      - name: Export genesis files
        run: |
          $HOME/manta build-spec --chain $CHAIN --raw > ./$CHAIN-genesis.json
          $HOME/manta export-genesis-state --chain $CHAIN > $CHAIN-genesis.state
          $HOME/manta export-genesis-wasm --chain $CHAIN > $CHAIN-genesis.wasm
          sha256sum $CHAIN-genesis.json $CHAIN-genesis.state $CHAIN-genesis.wasm | tee $CHAIN-genesis.sha256
      # upload artifacts
      - name: upload genesis
        uses: actions/upload-artifact@v2
        with:
          name: $CHAIN-genesis.json
          path: $HOME/$CHAIN-genesis.json
      - name: upload state
        uses: actions/upload-artifact@v2
        with:
          name: $CHAIN-genesis.state
          path: $HOME/$CHAIN-genesis.state
      - name: upload wasm
        uses: actions/upload-artifact@v2
        with:
          name: $CHAIN-genesis.wasm
          path: $HOME/$CHAIN-genesis.wasm
      # download artifacts and compare sha checksums
      - name: remove files
        run: |
          rm $HOME/$CHAIN-genesis.json
          rm $HOME/$CHAIN-genesis.state
          rm $HOME/$CHAIN-genesis.wasm
      - name: download json
        uses: actions/download-artifact@v3
        with:
          name: $CHAIN-genesis.json
      - name: download state
        uses: actions/download-artifact@v3
        with:
          name: $CHAIN-genesis.state
      - name: download wasm
        uses: actions/download-artifact@v3
        with:
          name: $CHAIN-genesis.wasm
      - name: compare sha checksums
        run: |
          sha256sum --check --strict $HOME/$CHAIN-genesis.sha256
