name: Rust

on:
  push:
    branches: [ manta ]
  pull_request:
    branches: [ manta ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      run: ./scripts/init.sh
    - name: build
      run: cargo build --verbose --release -p manta
    - name: test
      run: cargo test --verbose
